### ISSUE TITLE
Crash on joining the world

### ISSUE THREAD

**Issue by energy11a** [enjarai/OmniHopper#4]
[crash-2022-05-06_22.28.29-server.txt](https://github.com/enjarai/OmniHopper/files/8643204/crash-2022-05-06_22.28.29-server.txt)
https://drive.google.com/file/d/1jUEPmxp-LmN8ctLSSiYjhVK9XlNeCLti/view?usp=sharing

**Comment by enjarai** [comment]
This is an odd one. It seems like the crash is caused by a hopper containing a 19 stack of potions, which shouldn't be possible. For some reason this causes Fabric Transfer API to shit itself and it tries to insert negative items.

This means the problem lies with the Transfer API, so it isnt something I can fix. The easiest workaround for now would be to not use illegal itemstack amounts in the hoppers. 

If the higher stack amounts are made possible by another mod, the author has likely implemented it wrong and isn't communicating the changed stack size to other mods, so it'd be worth a shot to open an issue on their side.

I would however still consider this an issue with Transfer API as well, so I'd recommend opening an issue on the Fabric API issue tracker or mentioning the problem in #transfer-api-debating in the Fabric discord.
